import ProjectDescription

let workspace = Workspace(
	name: "Dorabangs",
	projects: [
		"Projects/App",
		"Projects/Core",
		"Projects/DesignSystem",
		"Projects/Features/Coordinator",
		"Projects/Features/Scene"
	],
	schemes: [
		.scheme(
			name: "Prod-Dorabangs",
			buildAction: .buildAction(targets: [.project(path: "./Projects/App", target: "Prod-Dorabangs")]),
			runAction: .runAction(
				configuration: .release,
				arguments: .arguments(environmentVariables: ["IDEPreferLogStreaming": "YES"])
			),
			archiveAction: .archiveAction(configuration: .release),
			profileAction: .profileAction(configuration: .release),
			analyzeAction: .analyzeAction(configuration: .release)
		),
		.scheme(
			name: "Dev-Dorabangs",
			buildAction: .buildAction(targets: [.project(path: "./Projects/App", target: "Dev-Dorabangs")]),
			runAction: .runAction(
				configuration: .debug,
				arguments: .arguments(environmentVariables: ["IDEPreferLogStreaming": "YES"])
			),
			archiveAction: .archiveAction(configuration: .debug),
			profileAction: .profileAction(configuration: .debug),
			analyzeAction: .analyzeAction(configuration: .debug)
		)
	],
	generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
